### ISSUE TITLE
Error in create_node

### ISSUE THREAD

**Issue by vgauthier** [StratusLab/libcloud-drivers#6]
Hi, 

When I use the function 'create_node' of the libcloud-driver it raise the following error:

cannot locate file schema.one
/usr/local/lib/python2.7/lib/site-packages/stratuslab_client-13.12.0-py2.7.egg/stratuslab/share/vm/schema.one

Instead of looking at this path which contains the file 'schema.one'
/usr/local/lib/python2.7/lib/site-packages/stratuslab_client-13.12.0-py2.7.egg/share/vm/schema.one

Regards, 
Vincent

**Comment by loomis** [comment]
There are multiple problems:
- The `schema.one` file packaged in the pypi package is not used because the file is not installed relative to one of the referenced packages in the search list.
- The unit test of libcloud picks up the `/var/lib/stratuslab/vm/schema.one` file installed via the RPM package.  Because of this, the tests (incorrectly) pass.
- `pip` and `easy_install` will install data files in different paths.  This should be avoided by using package_data instead.

For the last point see [this discussion](http://stackoverflow.com/questions/20298729/pip-installing-data-files-to-the-wrong-place) on StackOverflow and the [referenced email](https://groups.google.com/forum/#!msg/python-virtualenv/v5KJ78LP9Mo/OiBqMcYVFYAJ) when dealing with Python versions < 2.7.

**Comment by loomis** [comment]
This issue has been resolved via changes in the client.  Notably an addition search path for data files was added, so that it works with the RPM, pip, and easy_install installations.  Moreover tests for the RPM and easy_install installations have been added to the continuous integration server to ensure that these installation methods are tested.  More details can be found in the StratusLab/client#114 issue.
